spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/miaosha?characterEncoding=utf-8
    username : root
    password : root
  redis:
    host: 192.168.109.128
    port: 6379
    database: 9
    password: root
mybatis:
  mapper-locations : classpath:/mapper/*.xml