server:
  port: 8080

spring:
  application:
    name: vote-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  redis:
    password: root
    host: 192.168.109.128
    port: 6379
    database: 9
  rabbitmq:
    host: 192.168.109.128
    port: 5673

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chw.domain    # domain包下类重命名
